# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/omniauth_test_helper/all/omniauth_test_helper.rbi
#
# omniauth_test_helper-baeac5cf5190

module OmniAuthTestHelper
  def build_auth_hash(args = nil, generator); end
  def generators; end
  def generators=(val); end
  def mock_auth_hash(args = nil, &block); end
  def mock_auth_hash_on(context, args = nil, &block); end
  def self.generators; end
  def self.generators=(val); end
  def self.register_generator(&block); end
  def self.register_generator_on(context, &block); end
end
class OmniAuthTestHelper::AuthHashBuilder
  def build; end
  def build_extra; end
  def build_info; end
  def build_provider; end
  def build_raw_info(extra_keys); end
  def build_uid; end
  def initialize(an_args = nil); end
  def self.build(args = nil); end
end
class OmniAuthTestHelper::ValueGenerator
  def for(key, &block); end
  def generate; end
  def generate_for_key(key, intermediate); end
  def initialize; end
  def keys; end
end
